### ISSUE TITLE
Add `cursor: hand;` fallback

### ISSUE THREAD

**Issue by MadLittleMods** [markgoodyear/postcss-pointer#3]
This plugin should use the following cross-browser stack for IE8-. See [this Quirksmode compatibility table](http://quirksmode.org/css/user-interface/cursor.html#t08).

It would be even sweeter if you also turned `cursor: pointer;` into that same stack.

```
cursor: pointer;
cursor: hand;
```

**Comment by markgoodyear** [comment]
As this plugin is a "fun" plugin in response to the tweet in the readme, I feel providing a fallback for `cursor: pointer` would be suited for a separate plugin that focuses on old IE fallbacks.

Out of curiosity, as `cursor: pointer` is available IE6+, why would you need `cursor: hand`? It'd be simple to create a plugin to do this if you think it'd be beneficial however :smile:.

**Comment by MadLittleMods** [comment]
@markgoodyear Thanks for the quick response.

I don't think it would be worthwhile for a separate plugin; You already have claim to a pretty nice name that fits nicely for this.

The support for `cursor: pointer;` is good enough where it doesn't matter but it would be a nice bonus.

**Comment by markgoodyear** [comment]
The name would fit well yeah, however providing a fallback for IE 5.5, and a fun plugin to correct a potential typo would be serving two different purposes. For a fallback plugin, it could be something along the lines of `legacy-pointer`, or perhaps a play on words like `hand-pointer`, `handy-pointer`.
